### PR TITLE
[CAN2-17] added microcontroller bus interface reqs for review.

### PR DESCRIPTION
**Pull request by boomshakakan**
reqs for review by @eric-wagne .

### CODE REVIEW

**Comment by Nemiland** [comment]
How do I test BUSIF_R_01 and BUSIF_W_01?

**Comment by boomshakakan** [comment]
In retrospect those may not be testable. theres a way to word it better.

**Comment by boomshakakan** [comment]
Changed the requirements that were not testable.

**Comment by boomshakakan** [comment]
@eric-wagne pending your review.

**Review by eric-wagne — CHANGES_REQUESTED** [review]
[BUS_IF Requirements Checklist rev1.docx](https://github.com/ColinFritzLtts/CAN_Controller/files/4912981/BUS_IF.Requirements.Checklist.rev1.docx)

Reviewed by @eric-wagne . Minor revisions needed.

**Comment by boomshakakan** [comment]
Needs review. @eric-wagne

**Review by eric-wagne — APPROVED** [review]
[BUS_IF Requirements Checklist rev2.docx](https://github.com/ColinFritzLtts/CAN_Controller/files/4919369/BUS_IF.Requirements.Checklist.rev2.docx)

BUS_IF requirements APPROVED.

**Pull request merged**
