### PR TITLE
added spreadsheet with FIFO requirements for review [CAN2-18]

### PR DESCRIPTION
**Pull request by boomshakakan**
FIFO reqs needing review by @Nemiland

### CODE REVIEW

**Review by Nemiland — CHANGES_REQUESTED** [review]
[TxRx FIFO Requirements Checklist Rev. 0.docx](https://github.com/ColinFritzLtts/CAN_Controller/files/4892581/TxRx.FIFO.Requirements.Checklist.Rev.0.docx)
 Needs adjustments as described.

**Comment by boomshakakan** [comment]
added changes for further review @Nemiland

**Review by Nemiland — CHANGES_REQUESTED** [review]
[TxRx FIFO Requirements Checklist Rev. 1.docx](https://github.com/ColinFritzLtts/CAN_Controller/files/4897545/TxRx.FIFO.Requirements.Checklist.Rev.1.docx)
Some of the changes from Rev. 0 have not been addressed.

**Comment by boomshakakan** [comment]
Sent you the example fifo doc via email. @Nemiland

**Review by Nemiland — CHANGES_REQUESTED** [review]
[TxRx FIFO Requirements Checklist Rev. 2.docx](https://github.com/ColinFritzLtts/CAN_Controller/files/4898925/TxRx.FIFO.Requirements.Checklist.Rev.2.docx)
FIFO_W_03 and FIFO_R_03 don't work for all cases of full FIFO still.

**Comment by boomshakakan** [comment]
@Nemiland ready for review

**Review by Nemiland — APPROVED** [review]
[TxRx FIFO Requirements Checklist Rev. 3.docx](https://github.com/ColinFritzLtts/CAN_Controller/files/4899159/TxRx.FIFO.Requirements.Checklist.Rev.3.docx)
Good to go.

**Pull request merged**
